### ISSUE TITLE
autocomplete fails if model has parent ordering

### ISSUE THREAD

**Issue by ppeczek** [sehmaschine/django-grappelli#803] opened 2017-02-24 10:17 UTC
Try ordering in meta model by parent field:
```
class MyModel(models.Model):
    parent = models.ForeignKey(...)
    class Meta:
        ordering = ['parent__created_date']
```
Then autocomplete for MyModel fails with 500 error

**Comment by sehmaschine** [comment] 2017-03-29 08:58
I'm not able to reproduce this and it seems kind of weird. Are you saying that the ordering of `MyModel` interferes with the autocomplete for `parent` (because one has nothing to do with the other). Can you add more details and try to debug this?

**Comment by sehmaschine** [comment] 2017-05-25 11:54
closing this because no further details are given

**Closed by sehmaschine** 2017-05-25 11:54 UTC
