### ISSUE TITLE
LookupError with foreign key autocomplete: No installed app with label...

### ISSUE THREAD

**Issue by ivoras** [sehmaschine/django-grappelli#581] opened 2015-03-25 18:56 UTC
Hi,

I've raised the issue in the Google Group:
https://groups.google.com/forum/#!topic/django-grappelli/9kuOUbS4XEw

I'm copy-pasting it here for completeness sake:

I have an app with the label "k2" and both the source and the destination model are registered as Django Admin forms.
The ModelAdmin for the model which contains the foreign key has:

    autocomplete_lookup_fields = {
        'fk': ('product',),
        'm2m': [],
    }

The JavaScript code generates a lookup with the URL:

http://localhost:8000/grappelli/lookup/related/?object_id=&app_label=admink2&model_name=product

and the error is:

    HTTP 500: 
    LookupError at /grappelli/lookup/related/
    No installed app with label 'admink2'.

Note the app_label is "admink2". When I change it to "k2" manually, the query succeeds.

this is on django-grappelli==2.6.3

It is a strange error, and I even think it worked some time ago :(

I need to get this running quickly, so I've modified the grapelli/views/related.py as follows:

     48     def get_model(self):
     49         app_label = self.GET['app_label']
     50         if app_label.startswith('admin'):
     51             app_label = app_label[5:]
     52         self.model = models.get_model(app_label, self.GET['model_name'])                                                                          
     53         return self.model

I've added the the if app_label.startswith('admin')... code.
If this is correct-ish, please commit it.

**Comment by sehmaschine** [comment] 2015-03-25 20:03
did you define an app_label within your app?

the proposed patch is not the right way to solve this – but I actually doubt that we're talking about a bug here.

**Comment by sehmaschine** [comment] 2015-03-25 20:04
besides, which django version are you using?

**Comment by ivoras** [comment] 2015-03-25 21:27
I don't think so. Grepping for "app_label" in my entire app returns nothing. Do you have some other things for me to try?
This is Django 1.7.

**Comment by sehmaschine** [comment] 2015-03-26 08:57
Can you please send your INSTALLED_APPS, your URLs, the k2 model and k2 modeladmin (gist is preferred instead of pasting it here).

**Comment by ivoras** [comment] 2015-03-26 09:40
INSTALLED_APPS: https://gist.github.com/ivoras/a1ce61218c3f3c3bd6d7

app-level URLs: https://gist.github.com/ivoras/c54cf69c16d36a61665c

k2-level URLs: https://gist.github.com/ivoras/080d9da4f0f63c5c52f3

relevant models: https://gist.github.com/ivoras/13300bb8d547b2ea8c01

modeladmins: https://gist.github.com/ivoras/f748aff931d2a062c464

The ProductVariant model/admin form should autocomplete the "product" field.

**Comment by sehmaschine** [comment] 2015-03-26 10:02
your URLs look a bit strange to me ... both common/k2 start with``url(r'^',``. other than that, it looks ok to me. 

additional question: you don't have apps defined, have you? see https://docs.djangoproject.com/en/1.7/ref/applications/

**Comment by sehmaschine** [comment] 2015-03-27 15:20
Closing this since I'm pretty sure it's not a bug (besides, the mentioned functionality is covered with testcases).

**Closed by sehmaschine** 2015-03-27 15:20 UTC
