### ISSUE TITLE
ValueError: The file 'grappelli/jquery/i18n/ui.datepicker-en-us.js' could not be found

### ISSUE THREAD

**Issue by msamoylov** [sehmaschine/django-grappelli#577] opened 2015-03-05 20:01 UTC
VERSIONS: Grappelli 2.5.6, Django 1.6.10
    STATICFILES: ERROR
    CUSTOMIZATIONS: NONE

Running `./manage.py collectstatic && ./manage.py.compress` throws this:

    ValueError: The file 'grappelli/jquery/i18n/ui.datepicker-en-us.js' could not be found with <django.contrib.staticfiles.storage.CachedStaticFilesStorage object at 0x2d61550>.

**Comment by mpasternak** [comment] 2015-03-08 12:39
Hi, thank you for your report,

I'm using django-compressor too and it's pretty crucial to me to have it working. Please see my latest changes in my branch here https://github.com/sehmaschine/django-grappelli/pull/528#commits-pushed-8aa4387 and see if they fix anything.

@sehmaschine , do we want to support django-compressor out of the box?

Because, if we do, I'll just add a conditional there and it will cause generation of compressed javascript amalgamation file, that will contain all the translations for the jquery UI datepicker. 

The base.html will look like this (in pseudo-code, I don't remember the exact tags)

```
{% if COMPRESS_ENABLED %}
  {% compress js %}
  ...
  ... a list of all the jquery ui translation files, that will be compressed into one by django-compressor
  ...
  {% endcompress %}
{% else %}
  ... current code
{% endif %}
```

I guess jquery.ui.datepicker does not care about how many locales we include into Javascript code, as it uses only one of them. 

In my code, I am using customized, modified Grappelli HTML templates that use django-compressor heavily and in this case (localized calendar) I'd just include all the translations I want to support, perhaps in the page <head>, in the {%compress%} block.

**Comment by sehmaschine** [comment] 2015-03-09 16:45
@mpasternak I'm -1 on supporting django-compressor out of the box. We should try to limit any dependencies and it's pretty straightforward to get django-compressor up and running (well ... besides the mentioned error with translation files).

**Comment by msamoylov** [comment] 2015-03-09 16:49
Well, otherwise you're breaking a mature and popular third-party package.

**Comment by sehmaschine** [comment] 2015-03-09 16:53
@msamoylov Sorry, can't follow ...

**Comment by msamoylov** [comment] 2015-03-09 16:56
grappelli is missing the file named `grappelli/jquery/i18n/ui.datepicker-en-us.js` and that prevents compressing static files when `django.contrib.staticfiles.storage.CachedStaticFilesStorage` is enabled. So, it breaks a typical django-staticfiles deployment routine.

**Comment by sehmaschine** [comment] 2015-03-09 16:56
@msamoylov We'll remove ui localization ... see #528

**Comment by msamoylov** [comment] 2015-03-09 16:58
Perfect, thanks. Let's close this issue then.

**Comment by sehmaschine** [comment] 2015-03-09 16:59
@msamoylov Let's keep this issue for reference (other people might look for this error message as well). Will do the update within the next couple of days.

**Comment by sehmaschine** [comment] 2015-03-12 14:19
this is either not easy to solve or I am missing something. first, I'm not able to reproduce this (both collectstatic and compress works fine with my setup). second (and probably more important), there is no file ui.datepicker-en-us.js with jquery/i18n.

**Comment by msamoylov** [comment] 2015-03-12 14:25
django 1.6.10

**settings.py**

    LANGUAGE_CODE = 'en-US'

    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.CachedStaticFilesStorage'

    STATICFILES_FINDERS = (
        'django.contrib.staticfiles.finders.FileSystemFinder',
        'django.contrib.staticfiles.finders.AppDirectoriesFinder',
        'compressor.finders.CompressorFinder',
    )

    COMPRESS_CSS_FILTERS = [
        'compressor.filters.css_default.CssAbsoluteFilter',  
        'compressor.filters.cssmin.CSSMinFilter'
    ]

    COMPRESS_ENABLED = True
    COMPRESS_OFFLINE = True

**Comment by sehmaschine** [comment] 2015-03-12 14:33
No 'compress' template tags found in templates.

**Comment by sehmaschine** [comment] 2015-03-12 17:13
what I don't get here: why would compress look for ui.datepicker-en-us.js since that file is never being referenced within a termplate (as mentioned before, that file doesn't even exist with jqueryUI).

**Comment by mpasternak** [comment] 2015-03-12 17:56
Well, that file was referenced in my branch.

But  I also don't understand how django-compressor would look for files
outside {% compress %} block. Michael, did you modify files on your own?
12 mar 2015 18:13 "Patrick Kranzlmueller" <notifications@github.com>
napisał(a):

**Comment by msamoylov** [comment] 2015-03-12 18:17
I've got a legacy codebase, but there are no customizations. Now I'm trying to figure out which template is referencing this file.

**Comment by sehmaschine** [comment] 2015-03-13 08:46
I'm about to add a new release, but I would like this issue to be solved before. So please let me know if there's any additional information.

**Comment by mpasternak** [comment] 2015-03-13 09:48
I think it will be gone when you revert my commit with jQuery calendar
localization
13 mar 2015 09:46 "Patrick Kranzlmueller" <notifications@github.com>
napisał(a):

**Comment by sehmaschine** [comment] 2015-03-13 09:49
which commit exactly? the localized calendar has not been commited IMO.

**Comment by mpasternak** [comment] 2015-03-13 09:56
Well, this is somehow strange to me too, because I thought I was working in
a branch and people report bugs about my branch somehow... And those are
not people interested in jQuery ui localization... How would be that
possible?

If you did not merge my branch with master, I think grappelli is okay and
we can close this. As long as there are no special tags including jQuery ui
date picker localization at the bottom of base.html (or base_site.html),
there is no chance for this bug to occur.

Perhaps those guys downloaded my branch somehow but report issues here. No
idea.
13 mar 2015 10:50 "Patrick Kranzlmueller" <notifications@github.com>
napisał(a):

**Comment by sehmaschine** [comment] 2015-03-13 09:59
strange for me as well ... lets wait for another reply and see if someone might have worked with your branch instead of master/stable, because that would explain the issues. and that would also explain why I have never been able to reproduce this bug.

I wanna be sure about this before pushing another version to pypi.

**Comment by sehmaschine** [comment] 2015-03-27 15:15
I'm closing this since that is not an issue with the currently available branches IMO. Please reopen (with additional details) if you don't think this is solved.

**Closed by sehmaschine** 2015-03-27 15:15 UTC

**Comment by Chris7** [comment] 2016-02-10 00:00
It's because the pypi distribution is broken. The templates there include this:

{% if LANGUAGE_CODE %}
    {% with 'grappelli/jquery/i18n/ui.datepicker-'|add:LANGUAGE_CODE|add:'.js' as datepicker_url %}
    <script src="{% static datepicker_url %}" type="text/javascript"></script>
    {% endwith %}
    {% endif %}

which causes this error.

You can check it yourself here: https://pypi.python.org/pypi/django-grappelli/2.5.7

**Comment by Chris7** [comment] 2016-02-10 14:21
@msamoylov You can fix this by just adding an empty ui.datepicker-en-us.js to your static files under the path it needs.

**Comment by msamoylov** [comment] 2016-02-10 14:24
@Chris7 thanks you, captain. It was a year ago, just FYI.
