### ISSUE TITLE
Readonly field displayed incorrectly

### ISSUE THREAD

**Issue by lthamm** [sehmaschine/django-grappelli#990] opened 2022-02-23 16:26 UTC
Django version: 4.0
Grappelli 3.0.3 

**Problem:**
An admin.TabularInline has a readonly_field ("id"). This is rendered incorrectly. It works without grappelli and it used to work prior to Django 4.0.

**Output:**
```html
<div class="form-row grp-module grp-tbody has_original grp-dynamic-form" id="{ID}">
    <h3 style="display: none;">{MODEL_STR}</h3>
    {'name': 'id', 'label': 'id', 'help_text': '', 'field': 'id', 'is_hidden': True} 
  <div class="grp-tr">
        ....
  </div>
</div>
```

**Comment by sehmaschine** [comment] 2022-04-15 10:21
interesting – this works with my setup (I have 2 hidden input fields at the end of div).

what exactly is that dict after h3?

**Comment by sehmaschine** [comment] 2022-09-14 09:58
closing this since no further details have been given. please reopen with additional information if you think this is a bug which still exists.

**Comment by maldn** [comment] 2022-10-04 09:20
I stumbled over this one as well.
If you include "id" in the readonly_fields of the inline, or if you have has_change_permission() return False, the dict gets shown.
For me the solution is to just omit the "id" field

**Comment by sehmaschine** [comment] 2022-10-05 10:54
The "ID" field is always hidden, right? So this issue has nothing to do with readonly ... or do I miss something?

I am able to reproduce seeing the dict with adding an "ID" field to my inlines. I'm just trying to understand what exactly we're talking about.

**Closed** 2023-03-20 14:26 UTC
