### ISSUE TITLE
New RelatedObjectLookups.js in d1.8 causing related object functions to stop working

### ISSUE THREAD

**Issue by mochawich** [sehmaschine/django-grappelli#593] opened 2015-04-06 18:07 UTC
In Django 1.8 some of the functions in `RelatedObjectLookups.js` got changed which caused their functionality to stop working. eg. while adding a new related object the popup does not show.

**Comment by ngzhian** [comment] 2015-04-10 02:10
I opened up a PR attempting to fix this issue and also reconcile the `RelatedObjectLookups.js` in 1.8 with the one in grappelli.
I think the problem is an `onclick` handler on the `<a>` element, not the js file. The js file was actually pretty good in being [backwards compatible](https://github.com/django/django/blob/master/django/contrib/admin/static/admin/js/admin/RelatedObjectLookups.js#L138-L139)

**Comment by ngzhian** [comment] 2015-04-10 14:15
Progress update, think i found the issue here, tracked it down to [this commit in django](https://github.com/django/django/commit/68c9a72e29c929d896a25b3a0f566c09b6723dd4#diff-f42ac10b4a1091330b3ae0c3d0d0a7cf).

To summarize, that commit tries to decouple the JS and HTML of the widgets, thus they removed the `onclick` in the html [diff](https://github.com/django/django/commit/68c9a72e29c929d896a25b3a0f566c09b6723dd4#diff-f42ac10b4a1091330b3ae0c3d0d0a7cfL173), and instead attached a click event listener [here](https://github.com/django/django/commit/68c9a72e29c929d896a25b3a0f566c09b6723dd4#diff-e17ea8b1adbd222a1dc7ef37d03a0d49R78).

A possible fix is to copy those JS that adds the click handler into `change_form.html`. Will wor on that on the PR #595 .

**Comment by sehmaschine** [comment] 2015-04-13 12:14
Thanks a lot for looking into that. I'll check this issue once we work on compatibility with Django 1.8.

**Comment by ngzhian** [comment] 2015-04-13 13:01
@sehmaschine sure! Are there any issues I can help with? Would be great if you could @ ping me in those issues that you think can use an extra pair of eyes looking into, especially 1.8 compatibility blockers. Thanks

**Comment by sehmaschine** [comment] 2015-04-22 17:35
@ngzhian There's a new branch dev/2.7.x in order to work on compatibility with Django 1.8.

**Comment by sehmaschine** [comment] 2015-05-28 16:14
@ngzhian With branch stable/2.7.x (and dev/2.7.x) the related object functionality should be fine. For now, we didn't implement the new "edit" feature (we'll do that once all other bugs are resolved). Please give it a try and let me know if there are still issues.

**Comment by sehmaschine** [comment] 2015-09-07 09:53
closing this since no further feedback has been given (the edit feature is another issue anyway).

**Closed by sehmaschine** 2015-09-07 09:53 UTC
Labels: django 1.8
