### ISSUE TITLE
Saving an existing instance with existing inlines attempts to save these inlines again

### ISSUE THREAD

**Issue by ydaniv** [sehmaschine/django-grappelli#679] opened 2015-10-29 16:30 UTC
After upgrading from django from 1.7 to 1.8 and grappelli from 2.6 to 2.7, when attempting to save any form with inlines, of an object that already exist and has existing related inlines, the server attempts to save these related objects again.

This results in duplicate errors.

Downgrading django and grappelli with  practically same code (only templates settings were changed into 1.8's `TEMPLATES` style) works.

**Comment by sehmaschine** [comment] 2015-10-29 16:31
Not reproducable. Can you add details?

**Comment by ydaniv** [comment] 2015-10-29 16:43
Hard to say. All was working constantly until upgrade. Getting this issue on multiple change forms, perhaps everywhere there are inlines with any `unique_together` rules set on their related model.

The sent requests are practically identical, so probably not an issue in the form's data.

Also, I'm using django-extensions' PostgreSQLUUIDField for id's (latest version).

Any idea?

**Comment by sehmaschine** [comment] 2015-10-29 16:46
Well, I could guess ... but that probably doesn't help. Maybe you wanna add this question to the google-group and see if anyone has similar issues. And come back here once we're talking about an issue. Ok?

**Comment by ydaniv** [comment] 2015-10-29 16:47
:+1:

**Comment by sehmaschine** [comment] 2015-10-29 16:48
I'm closing this for now. Happy to reopen the ticket if we're able to narrow down the possible issue.

**Closed by sehmaschine** 2015-10-29 16:48 UTC

**Comment by sehmaschine** [comment] 2015-10-29 16:59
@ydaniv one note on this one: if the requests are identical, it seems to be a problem with django (because we just react on errors given by django). on the other hand, you could just try the original django-admin and check if the issue still exists ... if not, it's probably a grappelli issue.
