### ISSUE TITLE
autocomplete_lookup_fields can't use a field named 'related'

### ISSUE THREAD

**Issue by volksman** [sehmaschine/django-grappelli#843] opened 2018-04-23 14:36 UTC
If the field name is called 'related' the autocomplete_lookup_fields function fails.  Seems to be a reserved word for some reason but I can't really figure out why.  Any help would be appreciated.

**Comment by volksman** [comment] 2018-04-23 14:38
```class Listing(models.Model):
    name = models.CharFIeld(...)
    related = models.ManyToManyField('self')

    @staticmethod
    def autocomplete_search_field():
        return ("name__icontains")```

**Comment by volksman** [comment] 2018-04-23 15:12
I just migrated the field to a new name and I have the same issue.  Now wondering if it's because it's self referential?  I tried using a different m2m on the same model and it worked fine so it's something to do with this one field.

**Comment by sehmaschine** [comment] 2018-07-02 12:40
Just tested this with version 2.11.1 and it works fine with my setup.

**Comment by sehmaschine** [comment] 2018-09-24 12:43
I'm closing this for now since no further details are given and I'm not able to reproduce this issue.

**Closed by sehmaschine** 2018-09-24 12:43 UTC
Labels: discussion
