### ISSUE TITLE
raise VariableDoesNotExist("Failed lookup for key " django.template.base.VariableDoesNotExist: Failed lookup for key [grappelli_admin_title]

### ISSUE THREAD

**Issue by edugonch** [sehmaschine/django-grappelli#962] opened 2021-04-20 14:51 UTC
I update a project from Django 2.x to 3.1.6, this project used Suit as dashboard skin but as Suit is not compatible with 3.x branch I move it to Grappelli.

After making the instalation process I'm getting this error when trying to login:

```
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/cs3-s5PBYfou/lib/python3.9/site-packages/django/template/base.py", line 848, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [grappelli_admin_title] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: 'zqEgUhxCNbRy9Ui5TGfxk85B14jy7wvkVtiv2qjiKKnYPQYOffQInWdGJsW2dUx6'>, 'request': <WSGIRequest: POST '/cherokee2260/login/?next=/cherokee2260/'>, 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f792140ecd0>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f79224eb640>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f79214130d0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'form': <AdminAuthenticationForm bound=True, valid=False, fields=(username;password)>, 'view': <django.contrib.auth.views.LoginView object at 0x7f79213c5c70>, 'site_title': 'Django site admin', 'site_header': 'Django administration', 'site_url': '/', 'has_permission': False, 'available_apps': [], 'is_popup': False, 'is_nav_sidebar_enabled': True, 'title': 'Log in', 'app_path': '/cherokee2260/login/?next=/cherokee2260/', 'username': '', 'next': '/cherokee2260/', 'site': <Site: www.cspanalytics.com>, 'site_name': 'CS3', 'LANGUAGE_CODE': 'en-us', 'LANGUAGE_BIDI': False}, {'block': <Block Node: content. Contents: [<TextNode: '\n    <div class="g-d-c g-'>, <Variable Node: app_path>, <TextNode: '" method="post" novalidat'>, <django.template.defaulttags.CsrfTokenNode object at 0x7f79214395b0>, <TextNode: '\n            <fieldset cl'>, <IfNode>, <TextNode: '</span>\n                 '>, <django.templatetags.i18n.TranslateNode object at 0x7f7921439f70>, <TextNode: '</span>\n                <'>, <IfNode>, <TextNode: '\n                    '>, <IfNode>, <TextNode: '\n                    '>, <IfNode>, <TextNode: '\n                    <div'>, <IfNode>, <TextNode: '">\n                      '>, <Variable Node: form.username.label>, <TextNode: '</label>\n                '>, <IfNode>, <TextNode: '\n                    </di'>, <IfNode>, <TextNode: '">\n                      '>, <Variable Node: form.password.label>, <TextNode: '</label>\n                '>, <Variable Node: next>, <TextNode: '" />\n                    '>, <IfNode>, <TextNode: '\n                    </di'>, <django.template.defaulttags.URLNode object at 0x7f792135f550>, <TextNode: '\n                    '>, <IfNode>, <TextNode: '\n                </div>\n '>, <django.templatetags.i18n.TranslateNode object at 0x7f7921424790>, <TextNode: '" /></li>\n               '>]>}]
Exception while resolving variable 'error_message' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/cs3-s5PBYfou/lib/python3.9/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "/home/user/.local/share/virtualenvs/cs3-s5PBYfou/lib/python3.9/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'error_message'
```

I'm trying to find a solution but I'm lost, do you have any idea what this can be?

**Comment by sehmaschine** [comment] 2021-04-22 10:54
no idea what's happening here, but I'm pretty sure it's not related to grappelli.

**Comment by sehmaschine** [comment] 2021-07-12 14:46
admin title is set with settings and then used with a templatetag. this should work without any issues. I'm closing this for now since I'm not able to reproduce this – if you still think this is a bug, please reopen with additional details (it's probably easier for you to debug).

**Closed by sehmaschine** 2021-07-12 14:46 UTC
