### ISSUE TITLE
AdminDateWidget calendar prev next links are invisible in 3.0.8

### ISSUE THREAD

**Issue by AndrewYatskevich** [sehmaschine/django-grappelli#1057] opened 2024-06-18 12:23 UTC
Hello colleagues

We are using django-grappelli in our project. After updating to 3.0.8 the arrows of AdminDateWidget calendar got invisible. They don't show up in Google Chrome browser.

I've created repo to reproduce this bug. Please, check it out: https://github.com/AndrewYatskevich/bug-repro-invisible-arrows

OS Ubuntu 22.04.4 LTS
Browser Google Chrome Version 124.0.6367.118 (Official Build) (64-bit)

Best regards,
Andrew
![invisible-arrows](https://github.com/sehmaschine/django-grappelli/assets/102068396/ff636a55-3cfb-4026-8b64-6abb732485f9)

**Comment by parsch** [comment] 2024-06-18 14:01
@AndrewYatskevich I can't reproduce this quickly with my local setup, but have you checked whether the static files are loaded? The icon is part of a sprite map and should actually be visible if it can be loaded.

<img width="1114" alt="Bildschirmfoto 2024-06-18 um 16 00 51" src="https://github.com/sehmaschine/django-grappelli/assets/206830/6698fd9e-deda-472f-8721-f50b5f3db036">

**Comment by parsch** [comment] 2024-06-18 14:04
@AndrewYatskevich Sorry, can reproduce it with Chrome (used Firefox before). I will take a look at that.

**Comment by parsch** [comment] 2024-06-18 15:23
@AndrewYatskevich fixed in [stable/3.0.x](https://github.com/sehmaschine/django-grappelli/compare/stable/3.0.x), see commit above.

I couldn't find the exact reason but Chrome seems to have a problem rendering `background-image: url(my_transparent_icon.png)` with `background-color: transparent` defined separately. Using the shorthand `background: url(my_transparent_icon.png) x y, repeat, color)` avoids the problem.

**Closed by parsch** 2024-06-18 15:23 UTC

**Comment by AndrewYatskevich** [comment] 2024-06-19 08:08
@parsch Thanks for the quick fix!
