### ISSUE TITLE
JS issues in latest grappelli with inlines

### ISSUE THREAD

**Issue by Safrone** [sehmaschine/django-grappelli#941] opened 2020-04-22 17:52 UTC
I am getting these errors when adding new inline models in the admin on version 2.14.1

![Annotation 2020-04-22 134913](https://user-images.githubusercontent.com/14047377/80015683-1dee1f00-84a0-11ea-9db5-eff0e89fae24.png)

this does not happen on 2.13.4

**Comment by sehmaschine** [comment] 2020-05-14 11:01
cannot reproduce this. I have inline models with a datepicker and I do not get any errors. do you have additiona details?

**Comment by sehmaschine** [comment] 2020-05-14 11:16
what is djangoformset? does that interfere with grappelli?

**Comment by pasevin** [comment] 2020-05-14 12:27
I'm having the same error but it looks like it's stemming from [django-admin-nested](https://github.com/theatlantic/django-nested-admin) (at least for me) 
When I do replace this to standard ```TabularInline``` it works with no issues.

**Comment by Safrone** [comment] 2020-05-14 13:10
@pasevin I also was using django-admin-nested so it probably stems from there

**Comment by sehmaschine** [comment] 2020-07-21 08:49
so we can close this, right?

**Comment by pasevin** [comment] 2020-07-21 10:54
yes

**Closed** 2020-07-21 11:42 UTC
