### ISSUE TITLE
Runserver not working with Grappelli in installed apps

### ISSUE THREAD

**Issue by YvanRoozendaal** [sehmaschine/django-grappelli#944] opened 2020-05-27 13:52 UTC
I get a ""AUTH_USER_MODEL refers to model '%s' that has not been installed" % settings.AUTH_USER_MODEL"

But it is set and works properly without Grappelli (and always has). I made sure the installed apps list order is correct and tried variations to no avail. I also tried setting app_label and db_table as a workaround, but nothing helps. The User model properly extends AbstractBaseUser. I tried to collectstatic after installing the app, but this and makemigrations etc. all throw this error. 

Grappelli -v: 2.14.2
Django -v: 3.0.6

**Comment by sehmaschine** [comment] 2020-05-29 12:28
that`s strange, because we don't use `AUTH_USER_MODEL` at all – only with tests, but that should not affect runserver.

that said, do you have `django.contrib.auth` installed before `grappelli` with `INSTALLED_APPS`?

**Comment by YvanRoozendaal** [comment] 2020-05-30 15:30
Yes, I have. It breaks on get_user_model:
"venv/lib/python3.7/site-packages/grappelli/templatetags/grp_tags.py", line 20, in <module>
    User = get_user_model()"

"Generally speaking, it’s easiest to refer to the user model with the AUTH_USER_MODEL setting in code that’s executed at import time, however, it’s also possible to call get_user_model() while Django is importing models, so you could use models.ForeignKey(get_user_model(), ...)."

https://docs.djangoproject.com/en/3.0/topics/auth/customizing/#referencing-the-user-model

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Op vrijdag 29 mei 2020 14:28, Patrick Kranzlmueller <notifications@github.com> schreef:

**Comment by sehmaschine** [comment] 2020-06-02 10:36
Are you able to debug this issue and suggest a fix? Because I'm not able to reproduce this – actually, I still don't fully understand the issue, to be honest.

**Comment by sehmaschine** [comment] 2020-07-21 08:49
I'm about to close this one since no further details are given and I'm not able to reproduce this. I guess it's not related to grappelli but more of a django setup issue – but I might be missing something. I'll keep this issue open for another couple of days if someone wants to comment/help with this.

**Closed** 2020-08-25 12:14 UTC
