### ISSUE TITLE
Autocomplete broken after update

### ISSUE THREAD

**Issue by wjakob** [sehmaschine/django-grappelli#865] opened 2018-11-02 20:51 UTC
Hi,

after upgrading Django and Grappelli to the latest version, I noticed that autocomplete no longer works. The culprit seems to be the line

```python
def ajax_response(data):
    return HttpResponse(json.dumps(data, cls=DjangoJSONEncoder), content_type='application/javascript')
```
in ``related.py``, which throws the following exception even for very simple models:
```
Traceback (most recent call last):
  File "/Users/wjakob/Dropbox/projects/rgl-eb/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/wjakob/Dropbox/projects/rgl-eb/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/wjakob/Dropbox/projects/rgl-eb/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/wjakob/Dropbox/projects/rgl-eb/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/wjakob/Dropbox/projects/rgl-eb/lib/python3.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/wjakob/Dropbox/projects/rgl-eb/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/wjakob/Dropbox/projects/rgl-eb/lib/python3.7/site-packages/grappelli/views/related.py", 
line 256, in get
    return ajax_response(data)
  File "/Users/wjakob/Dropbox/projects/rgl-eb/lib/python3.7/site-packages/grappelli/views/related.py", line 47, in ajax_response
    return HttpResponse(json.dumps(data, cls=DjangoJSONEncoder), content_type='application/javascript')
  File "/Users/wjakob/.anaconda/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Users/wjakob/.anaconda/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/wjakob/.anaconda/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/wjakob/Dropbox/projects/rgl-eb/lib/python3.7/site-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/Users/wjakob/.anaconda/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Person is not JSON serializable
```

For reference, the definition of ``Person`` is:

```python
class Person(models.Model):
    first_name    = models.CharField('given name(s)', max_length=200)
    last_name     = models.CharField(max_length=200)
    webpage       = models.URLField('external web page', null=True, blank=True)
    github        = models.URLField('link to GitHub page', null=True, blank=True)
    email         = models.EmailField('email address', null=True, blank=True)
    app_label     = 'web'
    model_name    = 'person'

    def name(self):
        return self.first_name + ' ' + self.last_name

    def __str__(self):
        return self.name()

    @staticmethod
    def autocomplete_search_fields():
        return ("first_name__icontains", 'last_name__icontains',)

    class Meta:
        ordering = ['last_name', 'first_name']
```
I've tried stripping it down to just the name fields, and the exception still takes place (so I think it's a more fundamental issue).

**Comment by sehmaschine** [comment] 2018-11-03 11:16
You return `self.name` with Person, but there's no field `name`.

Am Fr., 2. Nov. 2018, 22:12 hat Wenzel Jakob <notifications@github.com>
geschrieben:

**Comment by wjakob** [comment] 2018-11-03 11:43
Hi Patrick,

apologies, I had removed some functions that I deemed irrelevant to the example. There was a name() function, which just concatenates the first and last name (fixed now). In any case, I don't think the issue are the particular fields/functions of this model. The problem still appears when I strip it down to just two strings (first and last name) and remove all auxiliary methods, so it's likely something more fundamental.

Thanks,
Wenzel

**Comment by sehmaschine** [comment] 2018-11-03 15:53
Which versions of Django and Grappelli are you using?

Am Sa., 3. Nov. 2018, 12:43 hat Wenzel Jakob <notifications@github.com>
geschrieben:

**Comment by cgabard** [comment] 2018-12-19 16:04
After investigation, I do not know if my problem is related to an update but I have use case that fail in the same way.

My problem is that the model I lookup for is a child of a multiple table inheritance. The parameter `to_field` in the get request is the name of the foreign key field, not the id. So when the json dump occur, a model instance is dumped.

To reproduce, we need three model: a base class, a child with multiple table inheritance and a model with the foreign key to the child model.

I do not know how to fix this because you retrieve the "to_field" from django raw_field search button that contain the FK field, not the linked id one. Maybe if we can manually override this parameter...

**Comment by sehmaschine** [comment] 2018-12-19 16:08
@cgabard can you please open a new ticket with additional details (e.g. the models, so we can reproduce it).

**Comment by sehmaschine** [comment] 2018-12-20 11:47
I just checked with all released versions (2.10, 2.11 and 2.12) and I'm not able to reproduce the problem. Anybody able to give more details?

**Comment by cgabard** [comment] 2018-12-20 13:35
Sure: #873

**Comment by sehmaschine** [comment] 2018-12-21 13:47
I'm closing this ticket, because I cannot reproduce the issue. Autocompletes do not work with multi-table inheritance though (but there's a different ticket). Please reopen if you still think there's an issue here.

**Closed by sehmaschine** 2018-12-21 13:47 UTC
