### ISSUE TITLE
Text in admin autocomplete fields not showing up.

### ISSUE THREAD

**Issue by sawan** [sehmaschine/django-grappelli#840] opened 2018-03-31 01:39 UTC
Hi,

I have a problem where the text generated by the autocomplete fk lookup is not being displayed in the form. This problem has appeared after upgrading to Django2.

I have searched the raw HTML of the page and the **text is there** -- it is simply not being rendered to the form.

This problem does not show up in my local dev environment (manage.py runserver) but shows up when running the site behind Nginx. I have verified:

1. XHR queries are being made and response is correct.
2. No missing JS.
3. No Missing CSS.
4. Text is actually present in the HTML, just not showing in the form.
5. Tested in 3 different browser.

Software versions:

Django==2.0.3
django-grappelli==2.11.1

Screenshot of the problem is attached; you can clearly see there are values (X) on the right of each row, but text is not being rendered.

Any idea?
![capturfiles-31-38-2018_12 38 55](https://user-images.githubusercontent.com/159342/38158465-7dd97d4a-34e0-11e8-9567-8538b38f73c4.png)

**Comment by sehmaschine** [comment] 2018-04-02 19:27
Sounds strange indeed.

Did you clear the browser cache?
Can you use the autocomplete (searching for something) and does it show the selected item?

**Comment by sawan** [comment] 2018-04-03 07:50
Yes, browser cache has been cleared.

No, using autocomplete does not show any text -- however I can see the network request and response being made! So it sis the display bit that is broken.

**Comment by sehmaschine** [comment] 2018-04-03 08:59
Hard to say what's wrong here since it works with your local setup and you don't see any JS errors. My guess is that there's an issue with your server setup (e.g. collectstatic not working as expected). Can you check if the same files are being loaded with your local/production setup?

**Comment by sehmaschine** [comment] 2018-07-02 10:57
Closing this since no further information has been given and we're not able to reproduce it.

**Closed by sehmaschine** 2018-07-02 10:57 UTC
